
broker:
  wsPort: 6032
  containerImage: embeddedenterprises/autobahnkreuz:v0.9.8

cmanager:
  containerImage: ovgucsworkshops/cmanager:v0.3.0
  userlandImage: ovgucsworkshops/git-userland:v0.2.1
  storageClass: ceph-ssd

webterminal:
  containerImage: ovgucsworkshops/web-terminal:latest

presentation:
  containerImage: ovgucsworkshops/git-workshop:latest

certificateIssuer: git-workshop-issuer

externalDomain: workshop.pattig.rocks
