# This file contains the deployment manifests for the centralized broker to communicate with all parties
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-broker
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-broker
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-broker
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    git-talk-service: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-broker
      app.kubernetes.io/instance: {{ .Release.Name }}-broker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-broker
        app.kubernetes.io/instance: {{ .Release.Name }}-broker
    spec:
      {{ if .Values.nodeSelector }}
      nodeSelector:
        {{ .Values.nodeSelector }}
      {{ end }}
      containers:
      - name: broker
        image: {{ .Values.broker.containerImage }}
        args: ["-r={{ .Values.config.realm }}", "--enable-wss=false", "--ws-port={{ .Values.broker.wsPort }}", "--enable-authorization=false", "--ticket-check-func=rocks.git.public.authenticate", "--ticket-get-role-func=rocks.git.public.get-roles", "--exclude-auth-role=system,trusted"]
        ports:
        - containerPort: {{ .Values.broker.wsPort }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-broker
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-broker
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-broker
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-broker
    app.kubernetes.io/instance: {{ .Release.Name }}-broker
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.broker.wsPort }}

