# This file contains all manifests related to the cManager that creates and manages the containers for the users.
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-cmanager
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["*"]

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-cmanager
automountServiceAccountToken: true

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-cmanager
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-cmanager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-cmanager
  apiGroup: rbac.authorization.k8s.io

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-cmanager
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-cmanager
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-cmanager
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-cmanager
      app.kubernetes.io/instance: {{ .Release.Name }}-cmanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-cmanager
        app.kubernetes.io/instance: {{ .Release.Name }}-cmanager
    spec:
      serviceAccountName: {{ .Release.Name }}-cmanager
      nodeSelector:
        {{ .Values.nodeSelector }}
      containers:
      - name: cmanager
        image: {{ .Values.cmanager.containerImage }}
        env:
        - name: POD_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: POD_STORAGE_CLASS
          value: {{ .Values.cmanager.storageClass }}
        - name: USER_IMAGE
          value: {{ .Values.cmanager.userlandImage }}
        - name: SERVICE_REALM
          value: {{ .Values.config.realm }}
        - name: SERVICE_BROKER_URL
          value: ws://{{ .Release.Name }}-broker
        - name: RUNPRIVILEGED
          value: {{ .Values.cmanager.spawnPrivileged | default "false" | quote }}
