{{- $Values := .Values -}}
{{- $Release := .Release -}}
{{- $Chart := .Chart -}}

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $Release.Name }}-cmanager
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ $Release.Name }}-cmanager
automountServiceAccountToken: true

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $Release.Name }}-cmanager
subjects:
- kind: ServiceAccount
  name: {{ $Release.Name }}-cmanager
  namespace: {{ $Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $Release.Name }}-cmanager
  apiGroup: rbac.authorization.k8s.io

---
