apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: {{ .Values.certificateIssuer }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: info@embedded.enterprises
    privateKeySecretRef:
      name: tls-{{ .Release.Name }}-{{ .Values.certificateIssuer }}-pkey
    http01: {}
