{{- $Values := .Values -}}
{{- $Release := .Release -}}
{{- $Chart := .Chart -}}

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $Release.Name }}-presentation
  labels:
    app.kubernetes.io/name: {{ $Release.Name }}-presentation
    helm.sh/chart: {{ $Chart.Name }}
    app.kubernetes.io/instance: {{ $Release.Name }}-presentation
    app.kubernetes.io/managed-by: {{ $Release.Service }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $Chart.Name }}-presentation
      app.kubernetes.io/instance: {{ $Release.Name }}-presentation
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $Chart.Name }}-presentation
        app.kubernetes.io/instance: {{ $Release.Name }}-presentation
    spec:
      containers:
      - name: {{ $Chart.Name }}-presentation
        image: {{ $Values.presentation.containerImage }}
        env:
        - name: "BROKER_URL"
          value: "wss://api.workshop.pattig.rocks"
        ports:
        - containerPort: 80
