{{- $Values := .Values -}}
{{- $Release := .Release -}}
{{- $Chart := .Chart -}}

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $Release.Name }}-cmanager
  labels:
    app.kubernetes.io/name: {{ $Release.Name }}-cmanager
    helm.sh/chart: {{ $Chart.Name }}
    app.kubernetes.io/instance: {{ $Release.Name }}-cmanager
    app.kubernetes.io/managed-by: {{ $Release.Service }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $Chart.Name }}-cmanager
      app.kubernetes.io/instance: {{ $Release.Name }}-cmanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $Chart.Name }}-cmanager
        app.kubernetes.io/instance: {{ $Release.Name }}-cmanager
    spec:
      serviceAccountName: {{ $Release.Name }}-cmanager
      containers:
      - name: {{ $Chart.Name }}-cmanager
        image: {{ $Values.cmanager.containerImage }}
        env:
        - name: USER_IMAGE
          value: ovgucsworkshops/git-userland:v0.1.13
        - name: SERVICE_REALM
          value: gittalk
        - name: SERVICE_BROKER_URL
          value: wss://api.workshop.pattig.rocks
