apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-ingress
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-ingress
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/issuer: {{ .Values.certificateIssuer }}
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
    ingress.kubernetes.io/ssl-redirect: "true"

spec:
  tls:
    - hosts:
      - {{ .Values.externalDomain }}
      - api.{{ .Values.externalDomain }}
      - presentation.{{ .Values.externalDomain }}
      secretName: tls-{{ .Release.Name }}-{{ .Values.certificateIssuer }}-dkey

  rules:
  - host: api.{{ .Values.externalDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}-broker
          servicePort: 80