{{- $Values := .Values -}}
{{- $Release := .Release -}}
{{- $Chart := .Chart -}}

kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $Release.Name }}-broker
  labels:
    app.kubernetes.io/name: {{ $Release.Name }}-broker
    helm.sh/chart: {{ $Chart.Name }}
    app.kubernetes.io/instance: {{ $Release.Name }}-broker
    app.kubernetes.io/managed-by: {{ $Release.Service }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $Chart.Name }}-broker
      app.kubernetes.io/instance: {{ $Release.Name }}-broker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $Chart.Name }}-broker
        app.kubernetes.io/instance: {{ $Release.Name }}-broker
    spec:
      containers:
      - name: {{ $Chart.Name }}-broker
        image: {{ $Values.broker.containerImage }}
        args: ["-r=gittalk", "--enable-wss=false", "--ws-port={{ $Values.broker.wsPort }}", "--enable-authorization=false", "--ticket-check-func=rocks.git.public.authenticate", "--ticket-get-role-func=rocks.git.public.get-roles", "--exclude-auth-role=system,trusted"]
        ports:
        - containerPort: {{ $Values.broker.wsPort }}
