{{- $Values := .Values -}}
{{- $Release := .Release -}}
{{- $Chart := .Chart -}}

kind: Service
apiVersion: v1
metadata:
  name: {{ $Release.Name }}-terminal
  labels:
    app.kubernetes.io/name: {{ $Chart.Name }}-terminal
    helm.sh/chart: {{ $Chart.Name }}
    app.kubernetes.io/instance: {{ $Release.Name }}-terminal
    app.kubernetes.io/managed-by: {{ $Release.Service }}

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ $Chart.Name }}-terminal
    app.kubernetes.io/instance: {{ $Release.Name }}-terminal
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

