# This file contains the deployment for the web based terminal used to interact by the users.
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-terminal
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-terminal
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-terminal
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}-terminal
      app.kubernetes.io/instance: {{ .Release.Name }}-terminal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}-terminal
        app.kubernetes.io/instance: {{ .Release.Name }}-terminal
    spec:
      {{ if .Values.nodeSelector }}
      nodeSelector:
        {{ .Values.nodeSelector }}
      {{ end }}
      containers:
      - name: terminal
        image: {{ .Values.webterminal.containerImage }}
        volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html/config.json
          subPath: config.json
        ports:
        - containerPort: 80
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-appconfig

---

kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-terminal
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-terminal
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}-terminal
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-terminal
    app.kubernetes.io/instance: {{ .Release.Name }}-terminal
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
